name: eventhub

services:
  backend:
    depends_on:
      - database
    image: backend:V1.0.0
    build:
      context: ./backend
    ports:
      - 5000:5000

  database:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
    ports:
      - 1433:1433