name: eventhub

services:
  backend:
    depends_on:
      - database
    container_name: backend
    build:
      context: ./backend
    ports:
      - 5000:5000

  database:
    image: mcr.microsoft.com/mssql/server
    container_name: database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
    ports:
      - 1433:1433